### ISSUE TITLE
Sample Play Issues

### ISSUE THREAD

**Issue by timway** [aruba/aruba-central-ansible-role#2]
``` ______________________________________________________
< TASK [Get all the UI and Template Groups on Central] >
 ------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

task path: /home/aruba-test/Documents/aruba-test/sample.yml:7
fatal: [aruba]: FAILED! => {"changed": false, "msg": "value of action must be one of: get_groups, get_group_mode, clone, update, create, delete, got: get"}
```

It's used in the sample plays:

```
---
-  hosts: all
   roles:
    - role: aruba-central-ansible-role
   tasks:
     - name: Get all the UI and Template Groups on Central
	   central_groups:
	     action: get
	     limit: 20
	     offset: 0
```

```
---
-  hosts: all
   roles:
    - role: arubanetworks.aos_wlan_role
   tasks:
     - name: Get all the UI and Template Groups on Central
	   central_groups:
	     action: get
	     limit: 20
	     offset: 0
```

The "action" does not seem to accurately reflect what the module is capable of. The spacing also appears incorrect - will try to addres in PR.
